# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'A3_PeterCorke.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(662, 483)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 20, 330, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 300, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 370, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 100, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 130, 361, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(130, 100, 131, 20))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(331, 20, 330, 422))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setText("")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_2.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.comboBox.raise_()
        self.label_6.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 662, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.comboBox.currentIndexChanged.connect(self.mostrar_diagrama)

    def mostrar_diagrama(self):
        pixmap = QtGui.QPixmap()
        
        if self.comboBox.currentIndex() == 1:  # Cartesiano
            pixmap.load("C:\\Users\\tato2\\Documents\\Universidad\\Algoritmos-de-Robotica\\Talleres\\Taller 2\\img\\Cartesiano.png")
            self.label_6.setPixmap(pixmap.scaled(
                self.label_6.width(), 
                self.label_6.height(), 
                QtCore.Qt.KeepAspectRatio, 
                QtCore.Qt.SmoothTransformation
            ))
            self.label_5.setText("Articulaciones: 3 (PPP)")
        elif self.comboBox.currentIndex() == 2:  # Esférico
            self.label_6.setPixmap(QtGui.QPixmap.fromImage(QtGui.QImage("img/Esferico.png")))
            self.label_5.setText("Articulaciones: 3 (RRP)")
        elif self.comboBox.currentIndex() == 3:  # Cilíndrico
            self.label_6.setPixmap(QtGui.QPixmap.fromImage(QtGui.QImage("img/Cilindrico.png")))
            self.label_5.setText("Articulaciones: 3 (RPP)")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:700;\">DIAGRAMA CINEMATICO<br/>&amp; <br/>POP-UP MENU </span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Integrantes: </p><p align=\"center\">Arellano Diego         |        Carrillo Esteban<br/>Fajardo Jean Pierre        |        Rodriguez Marlly    </p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/img/UNIVERSIDAD_ECCI.png\" width = \"300\"/></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Tipo de Robot:"))
        self.label_5.setText(_translate("MainWindow", "Articulaciones:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Seleccionar"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Cartesiano"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Esferico"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Cilindrico"))
import recurso_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
