# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'A4.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np
import matplotlib
matplotlib.use('Qt5Agg')
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 40, 461, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(100, 210, 160, 22))
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(100, 290, 160, 22))
        self.horizontalSlider_2.setMaximum(100)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(100, 370, 160, 22))
        self.horizontalSlider_3.setMaximum(100)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 166, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 250, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(160, 330, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(350, 130, 371, 371))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 410, 301, 111))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(390, 530, 381, 161))
        self.label_7.setObjectName("label_7")
        # Configuración de Matplotlib dentro de label_5
        self.figura = plt.figure()
        self.canvas = FigureCanvas(self.figura)
        self.ax = self.figura.add_subplot(111)
        
        # Layout para que el canvas ocupe el label_5
        self.layout_grafica = QtWidgets.QVBoxLayout(self.label_5)
        self.layout_grafica.addWidget(self.canvas)

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # --- CONEXIONES DINÁMICAS (Punto A.4) ---
        self.horizontalSlider.valueChanged.connect(self.actualizar_grafica)
        self.horizontalSlider_2.valueChanged.connect(self.actualizar_grafica)
        self.horizontalSlider_3.valueChanged.connect(self.actualizar_grafica)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        # Graficar inicialmente
        self.actualizar_grafica()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "CARGA Y DESCARGA CAPACITOR"))
        self.label_2.setText(_translate("MainWindow", "RESISTENCIA"))
        self.label_3.setText(_translate("MainWindow", "CAPACITOR"))
        self.label_4.setText(_translate("MainWindow", "VOLTAJE"))
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "CARGA Y DESCARGA CAPACITOR"))
        self.label_2.setText(_translate("MainWindow", "RESISTENCIA"))
        self.label_3.setText(_translate("MainWindow", "CAPACITOR"))
        self.label_4.setText(_translate("MainWindow", "VOLTAJE"))
        self.label_6.setText(_translate("MainWindow", "Marlly Johanna Rodriguez - 114061\n"
"Jean Pierre Fajardo Malagon - 113807\n"
"Juan Esteban Carrillo Galindo - 119042\n"
"Diego Alejandro Arellano - 110847"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/images.png\"/></p></body></html>"))
        import imagen_rc

    def actualizar_grafica(self):
        # Obtener valores de los sliders 
        R = self.horizontalSlider.value() * 1000  # Ohms
        C = self.horizontalSlider_2.value() * 1e-6 # Faradios
        V = self.horizontalSlider_3.value()        # Voltios
        
        tau = R * C # Constante de tiempo
        t = np.linspace(0, 5 * tau, 500)
        
        # Ecuaciones de carga y descarga 
        v_carga = V * (1 - np.exp(-t / tau))
        v_descarga = V * np.exp(-t / tau)
        
        self.ax.clear()
        self.ax.plot(t, v_carga, label='Carga', color='red')
        self.ax.plot(t, v_descarga, label='Descarga', color='blue')
        self.ax.set_title("Gráfica Dinámica Tiempo Real")
        self.ax.set_xlabel("Tiempo (s)")
        self.ax.set_ylabel("Voltaje (V)")
        self.ax.grid(True)
        self.ax.legend()
        self.canvas.draw()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
