# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'A5_ContornosImagenes.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtGui import QPixmap
import cv2
import numpy as np

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(662, 483)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 661, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(331, 370, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 320, 471, 26))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 370, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(341, 60, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(340, 90, 311, 221))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 90, 311, 221))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_2.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 662, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
## ------------------------------------------------------------------------------------------------------------------------------------
## ------------------------------------------------------------------------------------------------------------------------------------
        self.pushButton.clicked.connect(self.cargarImagen)

    def cargarImagen(self):
        # Abrir un cuadro de diálogo para seleccionar una imagen
        options = QFileDialog.Options()
        fileName, _ = QFileDialog.getOpenFileName(None, "Seleccionar Imagen", "", "Archivos de Imagen (*.png *.jpg *.bmp)", options=options)
        
        if fileName:
            # Cargar la iamgen usando OpenCV
            img = cv2.imread(fileName, cv2.IMREAD_UNCHANGED)
            
            if img is None:
                print(f"Error: No se pudo leer {fileName}")
                return
            
            # Imagen pre-procesada para mostrar en QLabel (sin contornos)
            img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGBA) # Convertir de BGR (OpenCV) a RGBA (Qt)
            
            alto, ancho, canales = img_rgb.shape # Obtener dimensiones y calcular bytes por línea
            bytes_por_linea = canales * ancho
    
            q_img1 = QtGui.QImage(img_rgb.data, ancho, alto, bytes_por_linea, QtGui.QImage.Format_RGBA8888) # Convertir a formato QImage para que Qt la entienda
            pixmap_img1 = QPixmap.fromImage(q_img1)

            self.label_7.setPixmap(pixmap_img1.scaled(self.label_7.size(), QtCore.Qt.KeepAspectRatio))

            # Coordenadas para guardar la imagen con contornos
            gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) # Convertir a escala de grises
            
            blur = cv2.medianBlur(gray, 3)
            _, thresh = cv2.threshold(blur, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
            
            # En lugar de dilate, usamos MORPH_CLOSE con un kernel pequeño
            # Esto une puntos cercanos pero intenta mantener el grosor original
            kernel = np.ones((3,3), np.uint8)
            thresh = cv2.morphologyEx(thresh, cv2.MORPH_CLOSE, kernel)

            contornos, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE) # Extracción de contornos (CHAIN_APPROX_NONE para tener todos los puntos)
            contornos, _ = cv2.findContours(thresh, cv2.RETR_LIST, cv2.CHAIN_APPROX_NONE)
            # Creamos el lienzo y las listas de puntos vacías
            lienzo = np.zeros((alto, ancho), dtype=np.uint8)
            puntos_totales = []

            for cnt in contornos:
                # Solo procesamos contornos con un área mínima (filtra ruido)
                if cv2.contourArea(cnt) > 20: 
                    # 1. Dibujar este contorno en el lienzo
                    cv2.drawContours(lienzo, [cnt], -1, (255), 2)
                    
                    # 2. Extraer puntos y acumularlos
                    pts = cnt.reshape(-1, 2)
                    puntos_totales.append(pts)

            # --- CONSOLIDAR PUNTOS X, Y ---
            if puntos_totales:
                # Unimos todos los fragmentos (cuerpo + patas + detalles) en un solo array
                todas_las_coords = np.vstack(puntos_totales)
                self.x = todas_las_coords[:, 0]
                self.y = todas_las_coords[:, 1]
                print(f"Total de puntos extraídos: {len(self.x)}")
            else:
                print("No se encontraron contornos válidos.")
                return











            
            # if not contornos:
            #     return None, None, None
            
            # cnt = max(contornos, key=cv2.contourArea)
            # puntos = cnt.reshape(-1, 2)
            # x = puntos[:, 0]
            # y = puntos[:, 1]


            # # Guardar la imagen con contornos dibujados
            # lienzo = np.zeros((alto, ancho), dtype=np.uint8) # Crear un lienzo negro del tamaño de la imagen original
            
            # puntos_reshaped = puntos.reshape((-1, 1, 2)).astype(np.int32) # Resonformar los puntos al formato que espera OpenCV: (n_puntos, 1, 2)
            
            # cv2.drawContours(lienzo, [puntos_reshaped], -1, (255), 2) # Dibujar el contorno (el -1 indica que dibuje todos, el 255 es color blanco, 2 es grosor)
              
              

            # Presentar imagen con contornos
            lienzo_rgb = cv2.cvtColor(lienzo, cv2.COLOR_GRAY2RGBA) # Conver
            
            alto, ancho, canales = lienzo_rgb.shape # Obtener dimensiones y calcular bytes por línea
            bytes_por_linea = canales * ancho
    
            q_img2 = QtGui.QImage(lienzo_rgb.data, ancho, alto, bytes_por_linea, QtGui.QImage.Format_RGBA8888) # Convertir a formato QImage para que Qt la entienda
            pixmap_img2 = QPixmap.fromImage(q_img2)

            self.label_6.setPixmap(pixmap_img2.scaled(self.label_6.size(), QtCore.Qt.KeepAspectRatio))
            
            # Convertir la imagen a escala de grises
            # gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
            
            # # Aplicar un umbral para obtener una imagen binaria
            # _, thresh = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)
            
            # # Encontrar los contornos en la imagen binaria
            # contours, _ = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
            
            # # Dibujar los contornos en la imagen original
            # cv2.drawContours(image, contours, -1, (0, 255, 0), 3)
            
            # # Convertir la imagen a formato RGB para mostrarla en QLabel
            # image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
            # height, width, channel = image_rgb.shape
            # bytesPerLine = 3 * width
            # qImg = QtGui.QImage(image_rgb.data, width, height, bytesPerLine, QtGui.QImage.Format_RGB888)
            # pixmap = QPixmap.fromImage(qImg)
            # self.label_6.setPixmap(pixmap.scaled(self.label_6.size(), QtCore.Qt.KeepAspectRatio))

## ------------------------------------------------------------------------------------------------------------------------------------
## ------------------------------------------------------------------------------------------------------------------------------------

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:700;\">CONTORNOS DE IMAGENES</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Integrantes: </p><p align=\"center\">Arellano Diego         |        Carrillo Esteban<br/>Fajardo Jean Pierre        |        Rodriguez Marlly    </p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Cargar Imagen"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/img/UNIVERSIDAD_ECCI.png\" width = \"300\"/></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Imagen Subida:"))
        self.label_5.setText(_translate("MainWindow", "Imagen Subida:"))
import recurso_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
