# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'STEPPER2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import RPi.GPIO as GPIO
import time

# Configuración de Pines GPIO
#P_DIR = 24 #PIN FISICO 18
#P_STEP = 25 #PIN FISICO 22
#PASOS_POR_VUELTA = 200 # Estándar para NEMA 17

# Configuración basada en el CNC Shield (Eje X)
P_STEP = 17
P_DIR = 27
P_ENABLE = 22 # El shield requiere poner este pin en LOW para activar motores

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(736, 432)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 20, 451, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(80, 150, 201, 71))
        self.textEdit.setObjectName("textEdit")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 150, 311, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 232, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 105, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 290, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(360, 270, 331, 71))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 736, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # --- INICIALIZACIÓN GPIO Y CONEXIÓN ---
        self.configurar_hardware()
        self.pushButton.clicked.connect(self.mover_motor)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "CONTROL GIRO MOTOR PASO A PASO "))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "MOVER"))
        self.label_3.setText(_translate("MainWindow", "CANTIDAD DE VUELTAS"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/UNIVERSIDAD_ECCI.png\" width = \"300\"/></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Integrantes: </p><p align=\"center\">Arellano Diego         |        Carrillo Esteban<br/>Fajardo Jean Pierre        |        Rodriguez Marlly    </p></body></html>"))
    #def configurar_hardware(self):
        #"""Configura los pines de la Raspberry Pi"""
        #GPIO.setmode(GPIO.BCM)
        #GPIO.setwarnings(False)
       # GPIO.setup(P_DIR, GPIO.OUT)
       # GPIO.setup(P_STEP, GPIO.OUT)

    def configurar_hardware(self):
        GPIO.setmode(GPIO.BCM) #
        GPIO.setwarnings(False)
        GPIO.setup(P_DIR, GPIO.OUT)
        GPIO.setup(P_STEP, GPIO.OUT)
        GPIO.setup(P_ENABLE, GPIO.OUT)
        # En el CNC Shield, el pin EN debe estar en LOW para que el driver funcione
        GPIO.output(P_ENABLE, GPIO.LOW)

    #def mover_motor(self):
        #"""Lógica para accionar el movimiento"""
        #try:
            # Leer valor del Edit Text
            #entrada = self.textEdit.toPlainText().strip()
            #vueltas = float(entrada)
            
            # Calcular pasos totales
           # pasos_totales = int(abs(vueltas) * PASOS_POR_VUELTA)
            
            # Definir dirección (Horario si es positivo)
            #GPIO.output(P_DIR, GPIO.HIGH if vueltas > 0 else GPIO.LOW)
            
            #self.label_2.setText(f"Moviendo {vueltas} vueltas...")
            #QtWidgets.QApplication.processEvents() # Actualizar interfaz

            # Generar pulsos de movimiento
            #for _ in range(pasos_totales):
                #GPIO.output(P_STEP, GPIO.HIGH)
                #time.sleep(0.001) # Velocidad del pulso
                #GPIO.output(P_STEP, GPIO.LOW)
                #time.sleep(0.001)
            
            #self.label_2.setText(f"Éxito: Se completaron {vueltas} vueltas.")
            
        #except ValueError:
           # self.label_2.setText("Error: Ingrese un número válido.")
       # except Exception as e:
          #  self.label_2.setText(f"Error crítico: {str(e)}") 

    def mover_motor(self):
        try:
            # Leer valor del Edit Text
            entrada = self.textEdit.toPlainText().strip()
            vueltas = float(entrada)
            pasos_totales = int(abs(vueltas) * 200) # NEMA 17 estándar
            
            # Definir dirección
            GPIO.output(P_DIR, GPIO.HIGH if vueltas > 0 else GPIO.LOW)
            
            self.label_2.setText(f"Girando eje X: {vueltas} vueltas")
            QtWidgets.QApplication.processEvents()

            for _ in range(pasos_totales):
                GPIO.output(P_STEP, GPIO.HIGH)
                time.sleep(0.001)
                GPIO.output(P_STEP, GPIO.LOW)
                time.sleep(0.001)
            
            self.label_2.setText(f"Proceso finalizado con éxito.") #
            
        except ValueError:
            self.label_2.setText("Error: Ingrese un número válido.") #   
import ci_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    #sys.exit(app.exec_())
    try:
        sys.exit(app.exec_())
    finally:
       GPIO.cleanup() # Limpiar pines al cerrar
